"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TPFtAccessControl__factory = exports.TPFt__factory = exports.SwapOneStep__factory = exports.RealTokenizado__factory = exports.RealDigitalEnableAccount__factory = exports.RealDigital__factory = exports.KeyDictionary__factory = exports.ITPFt__factory = exports.CBDCAccessControl__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var CBDCAccessControl__factory_1 = require("./CBDCAccessControl__factory");
Object.defineProperty(exports, "CBDCAccessControl__factory", { enumerable: true, get: function () { return CBDCAccessControl__factory_1.CBDCAccessControl__factory; } });
var ITPFt__factory_1 = require("./ITPFt__factory");
Object.defineProperty(exports, "ITPFt__factory", { enumerable: true, get: function () { return ITPFt__factory_1.ITPFt__factory; } });
var KeyDictionary__factory_1 = require("./KeyDictionary__factory");
Object.defineProperty(exports, "KeyDictionary__factory", { enumerable: true, get: function () { return KeyDictionary__factory_1.KeyDictionary__factory; } });
var RealDigital__factory_1 = require("./RealDigital__factory");
Object.defineProperty(exports, "RealDigital__factory", { enumerable: true, get: function () { return RealDigital__factory_1.RealDigital__factory; } });
var RealDigitalEnableAccount__factory_1 = require("./RealDigitalEnableAccount__factory");
Object.defineProperty(exports, "RealDigitalEnableAccount__factory", { enumerable: true, get: function () { return RealDigitalEnableAccount__factory_1.RealDigitalEnableAccount__factory; } });
var RealTokenizado__factory_1 = require("./RealTokenizado__factory");
Object.defineProperty(exports, "RealTokenizado__factory", { enumerable: true, get: function () { return RealTokenizado__factory_1.RealTokenizado__factory; } });
var SwapOneStep__factory_1 = require("./SwapOneStep__factory");
Object.defineProperty(exports, "SwapOneStep__factory", { enumerable: true, get: function () { return SwapOneStep__factory_1.SwapOneStep__factory; } });
var TPFt__factory_1 = require("./TPFt__factory");
Object.defineProperty(exports, "TPFt__factory", { enumerable: true, get: function () { return TPFt__factory_1.TPFt__factory; } });
var TPFtAccessControl__factory_1 = require("./TPFtAccessControl__factory");
Object.defineProperty(exports, "TPFtAccessControl__factory", { enumerable: true, get: function () { return TPFtAccessControl__factory_1.TPFtAccessControl__factory; } });
