"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.TesouroDireto__factory = exports.ITesouroDireto__factory = exports.drex = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.drex = __importStar(require("./drex"));
var ITesouroDireto__factory_1 = require("./ITesouroDireto__factory");
Object.defineProperty(exports, "ITesouroDireto__factory", { enumerable: true, get: function () { return ITesouroDireto__factory_1.ITesouroDireto__factory; } });
var TesouroDireto__factory_1 = require("./TesouroDireto__factory");
Object.defineProperty(exports, "TesouroDireto__factory", { enumerable: true, get: function () { return TesouroDireto__factory_1.TesouroDireto__factory; } });
