/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as drex from "./drex";
export { ITesouroDireto__factory } from "./ITesouroDireto__factory";
export { TesouroDireto__factory } from "./TesouroDireto__factory";
