"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ITesouroDireto__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [
            {
                internalType: "uint256",
                name: "tokenA",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "initialPriceA",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "swapFee",
                type: "uint256",
            },
        ],
        name: "createLiquidtyPool",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];
class ITesouroDireto__factory {
    static createInterface() {
        return new ethers_1.Interface(_abi);
    }
    static connect(address, runner) {
        return new ethers_1.Contract(address, _abi, runner);
    }
}
exports.ITesouroDireto__factory = ITesouroDireto__factory;
ITesouroDireto__factory.abi = _abi;
