/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as drex from "./drex";
export type { drex };
export type { ITesouroDireto } from "./ITesouroDireto";
export type { TesouroDireto } from "./TesouroDireto";
