"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.TesouroDireto__factory = exports.ITesouroDireto__factory = exports.TPFtAccessControl__factory = exports.TPFt__factory = exports.SwapOneStep__factory = exports.RealTokenizado__factory = exports.RealDigitalEnableAccount__factory = exports.RealDigital__factory = exports.KeyDictionary__factory = exports.ITPFt__factory = exports.CBDCAccessControl__factory = exports.Pausable__factory = exports.Math__factory = exports.IERC165__factory = exports.ERC165__factory = exports.IERC20__factory = exports.IERC20Metadata__factory = exports.ERC20__factory = exports.IERC1155Receiver__factory = exports.IERC1155__factory = exports.IERC1155MetadataURI__factory = exports.ERC1155__factory = exports.IERC721Errors__factory = exports.IERC20Errors__factory = exports.IERC1155Errors__factory = exports.IAccessControl__factory = exports.AccessControl__factory = exports.factories = void 0;
exports.factories = __importStar(require("./factories"));
var AccessControl__factory_1 = require("./factories/@openzeppelin/contracts/access/AccessControl__factory");
Object.defineProperty(exports, "AccessControl__factory", { enumerable: true, get: function () { return AccessControl__factory_1.AccessControl__factory; } });
var IAccessControl__factory_1 = require("./factories/@openzeppelin/contracts/access/IAccessControl__factory");
Object.defineProperty(exports, "IAccessControl__factory", { enumerable: true, get: function () { return IAccessControl__factory_1.IAccessControl__factory; } });
var IERC1155Errors__factory_1 = require("./factories/@openzeppelin/contracts/interfaces/draft-IERC6093.sol/IERC1155Errors__factory");
Object.defineProperty(exports, "IERC1155Errors__factory", { enumerable: true, get: function () { return IERC1155Errors__factory_1.IERC1155Errors__factory; } });
var IERC20Errors__factory_1 = require("./factories/@openzeppelin/contracts/interfaces/draft-IERC6093.sol/IERC20Errors__factory");
Object.defineProperty(exports, "IERC20Errors__factory", { enumerable: true, get: function () { return IERC20Errors__factory_1.IERC20Errors__factory; } });
var IERC721Errors__factory_1 = require("./factories/@openzeppelin/contracts/interfaces/draft-IERC6093.sol/IERC721Errors__factory");
Object.defineProperty(exports, "IERC721Errors__factory", { enumerable: true, get: function () { return IERC721Errors__factory_1.IERC721Errors__factory; } });
var ERC1155__factory_1 = require("./factories/@openzeppelin/contracts/token/ERC1155/ERC1155__factory");
Object.defineProperty(exports, "ERC1155__factory", { enumerable: true, get: function () { return ERC1155__factory_1.ERC1155__factory; } });
var IERC1155MetadataURI__factory_1 = require("./factories/@openzeppelin/contracts/token/ERC1155/extensions/IERC1155MetadataURI__factory");
Object.defineProperty(exports, "IERC1155MetadataURI__factory", { enumerable: true, get: function () { return IERC1155MetadataURI__factory_1.IERC1155MetadataURI__factory; } });
var IERC1155__factory_1 = require("./factories/@openzeppelin/contracts/token/ERC1155/IERC1155__factory");
Object.defineProperty(exports, "IERC1155__factory", { enumerable: true, get: function () { return IERC1155__factory_1.IERC1155__factory; } });
var IERC1155Receiver__factory_1 = require("./factories/@openzeppelin/contracts/token/ERC1155/IERC1155Receiver__factory");
Object.defineProperty(exports, "IERC1155Receiver__factory", { enumerable: true, get: function () { return IERC1155Receiver__factory_1.IERC1155Receiver__factory; } });
var ERC20__factory_1 = require("./factories/@openzeppelin/contracts/token/ERC20/ERC20__factory");
Object.defineProperty(exports, "ERC20__factory", { enumerable: true, get: function () { return ERC20__factory_1.ERC20__factory; } });
var IERC20Metadata__factory_1 = require("./factories/@openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata__factory");
Object.defineProperty(exports, "IERC20Metadata__factory", { enumerable: true, get: function () { return IERC20Metadata__factory_1.IERC20Metadata__factory; } });
var IERC20__factory_1 = require("./factories/@openzeppelin/contracts/token/ERC20/IERC20__factory");
Object.defineProperty(exports, "IERC20__factory", { enumerable: true, get: function () { return IERC20__factory_1.IERC20__factory; } });
var ERC165__factory_1 = require("./factories/@openzeppelin/contracts/utils/introspection/ERC165__factory");
Object.defineProperty(exports, "ERC165__factory", { enumerable: true, get: function () { return ERC165__factory_1.ERC165__factory; } });
var IERC165__factory_1 = require("./factories/@openzeppelin/contracts/utils/introspection/IERC165__factory");
Object.defineProperty(exports, "IERC165__factory", { enumerable: true, get: function () { return IERC165__factory_1.IERC165__factory; } });
var Math__factory_1 = require("./factories/@openzeppelin/contracts/utils/math/Math__factory");
Object.defineProperty(exports, "Math__factory", { enumerable: true, get: function () { return Math__factory_1.Math__factory; } });
var Pausable__factory_1 = require("./factories/@openzeppelin/contracts/utils/Pausable__factory");
Object.defineProperty(exports, "Pausable__factory", { enumerable: true, get: function () { return Pausable__factory_1.Pausable__factory; } });
var CBDCAccessControl__factory_1 = require("./factories/contracts/drex/CBDCAccessControl__factory");
Object.defineProperty(exports, "CBDCAccessControl__factory", { enumerable: true, get: function () { return CBDCAccessControl__factory_1.CBDCAccessControl__factory; } });
var ITPFt__factory_1 = require("./factories/contracts/drex/ITPFt__factory");
Object.defineProperty(exports, "ITPFt__factory", { enumerable: true, get: function () { return ITPFt__factory_1.ITPFt__factory; } });
var KeyDictionary__factory_1 = require("./factories/contracts/drex/KeyDictionary__factory");
Object.defineProperty(exports, "KeyDictionary__factory", { enumerable: true, get: function () { return KeyDictionary__factory_1.KeyDictionary__factory; } });
var RealDigital__factory_1 = require("./factories/contracts/drex/RealDigital__factory");
Object.defineProperty(exports, "RealDigital__factory", { enumerable: true, get: function () { return RealDigital__factory_1.RealDigital__factory; } });
var RealDigitalEnableAccount__factory_1 = require("./factories/contracts/drex/RealDigitalEnableAccount__factory");
Object.defineProperty(exports, "RealDigitalEnableAccount__factory", { enumerable: true, get: function () { return RealDigitalEnableAccount__factory_1.RealDigitalEnableAccount__factory; } });
var RealTokenizado__factory_1 = require("./factories/contracts/drex/RealTokenizado__factory");
Object.defineProperty(exports, "RealTokenizado__factory", { enumerable: true, get: function () { return RealTokenizado__factory_1.RealTokenizado__factory; } });
var SwapOneStep__factory_1 = require("./factories/contracts/drex/SwapOneStep__factory");
Object.defineProperty(exports, "SwapOneStep__factory", { enumerable: true, get: function () { return SwapOneStep__factory_1.SwapOneStep__factory; } });
var TPFt__factory_1 = require("./factories/contracts/drex/TPFt__factory");
Object.defineProperty(exports, "TPFt__factory", { enumerable: true, get: function () { return TPFt__factory_1.TPFt__factory; } });
var TPFtAccessControl__factory_1 = require("./factories/contracts/drex/TPFtAccessControl__factory");
Object.defineProperty(exports, "TPFtAccessControl__factory", { enumerable: true, get: function () { return TPFtAccessControl__factory_1.TPFtAccessControl__factory; } });
var ITesouroDireto__factory_1 = require("./factories/contracts/ITesouroDireto__factory");
Object.defineProperty(exports, "ITesouroDireto__factory", { enumerable: true, get: function () { return ITesouroDireto__factory_1.ITesouroDireto__factory; } });
var TesouroDireto__factory_1 = require("./factories/contracts/TesouroDireto__factory");
Object.defineProperty(exports, "TesouroDireto__factory", { enumerable: true, get: function () { return TesouroDireto__factory_1.TesouroDireto__factory; } });
